apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: grafana-storage
  namespace: omniflow-monitoring

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi
