apiVersion: v1
kind: ConfigMap
metadata:
  name: omniflow-config
  namespace: omniflow

data:

  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"

  REDIS_HOST: redis
  REDIS_PORT: "6379"

  JWT_ALGORITHM: HS256
  JWT_EXPIRE_MINUTES: "60"

  FRONTEND_URL: http://gateway

  AUTH_SERVICE_URL: http://10.43.38.73:8001
  FORM_SERVICE_URL: http://10.43.163.235:8002
  WORKFLOW_SERVICE_URL: http://10.43.127.43:8003
  TASK_SERVICE_URL: http://10.43.43.252:8004
  NOTIFICATION_SERVICE_URL: http://10.43.111.28:8005