apiVersion: v1
kind: Secret
metadata:
  name: omniflow-secret
  namespace: omniflow

type: Opaque

stringData:

  POSTGRES_USER: pk_user
  POSTGRES_PASSWORD: pk_password
  POSTGRES_DB: pk_user

  JWT_SECRET: dev_secret_key

  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  GOOGLE_REDIRECT_URI: ""

  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""
  GITHUB_REDIRECT_URI: ""

  RESEND_API_KEY: ""

  MAGIC_LINK_SECRET: ""
  MAGIC_LINK_FROM_EMAIL: ""

  GEMINI_API_KEY: ""