"""initial_task_schema

Revision ID: 953eda04b1f4
Revises:
Create Date: 2026-05-26 03:47:32.359879

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = "953eda04b1f4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Set search path for PostgreSQL
    conn = op.get_bind()
    if conn.dialect.name != "sqlite":
        schema = "task_schema"
        conn.execute(sa.text(f"CREATE SCHEMA IF NOT EXISTS {schema}"))
        conn.execute(sa.text(f"SET search_path TO {schema}"))

    # Use sa.func.now() for better cross-dialect compatibility
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "institution_id", sa.Integer(), nullable=False, server_default=sa.text("1")
        ),
        sa.Column("submission_id", sa.String(), nullable=False),
        sa.Column("step_id", sa.String(), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("actor_id", sa.String(), nullable=False),
        sa.Column("actor_role", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_submission_id"),
        "audit_events",
        ["submission_id"],
        unique=False,
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "institution_id", sa.Integer(), nullable=False, server_default=sa.text("1")
        ),
        sa.Column("workflow_id", sa.String(), nullable=False),
        sa.Column("form_id", sa.String(), nullable=True),
        sa.Column("current_step_id", sa.String(), nullable=True),
        sa.Column("submitted_by", sa.String(), nullable=False),
        sa.Column("form_data", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_submissions_submitted_by"),
        "submissions",
        ["submitted_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_submissions_workflow_id"), "submissions", ["workflow_id"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "institution_id", sa.Integer(), nullable=False, server_default=sa.text("1")
        ),
        sa.Column("submission_id", sa.String(), nullable=False),
        sa.Column("assigned_role", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tasks_assigned_role"), "tasks", ["assigned_role"], unique=False
    )
    op.create_index(
        op.f("ix_tasks_submission_id"), "tasks", ["submission_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_submission_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_assigned_role"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_submissions_workflow_id"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_submitted_by"), table_name="submissions")
    op.drop_table("submissions")
    op.drop_index(op.f("ix_audit_events_submission_id"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
